/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/scene.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Classroom(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/Room.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Wall001" position={[4.671, -6.587, 19.874]}>
          <group name="Left_Angle" position={[0, 0, -0.152]} />
          <group name="OBJ_PROMPTS" position={[-0.004, 0, 0.005]} />
          <group name="OBJ_Y" position={[0, 0, -0.152]} />
        </group>
        <group name="Sketchfab_model" position={[2.14, -4.886, 5.063]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="adeb93b16b1343ce9259f3bc30ece086fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode" />
          </group>
        </group>
        <group name="Sketchfab_model002" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="adeb93b16b1343ce9259f3bc30ece086fbx001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode002" />
          </group>
        </group>
        <group name="Sketchfab_model001" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode001">
              <group name="#WIN0003_Frame001" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model003" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode003">
              <group name="#WIN0003_Frame" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model004" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx002" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode004">
              <group name="#WIN0003_Frame002" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model006" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx004" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode006">
              <group name="#WIN0003_Frame004" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model007" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx005" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode007">
              <group name="#WIN0003_Frame005" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model009" position={[6.334, -6.587, 19.879]} rotation={[Math.PI / 2, 0, 0]} scale={-1}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx007" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode009">
              <group name="#WIN0003_Frame007" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model010" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="44c15676bd92436aa0e032a2683df647fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode010">
              <group name="tvCabinet3" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model011" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="ACfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode011">
              <group name="AC" />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model012" position={[4.667, -6.587, 8.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.335, 0.334, 0.402]}>
          <group name="ACfbx001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode012">
              <group name="AC001" />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model015" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="ClassRoom+Hall+004_4" scale={0.001}>
                <group name="Items004_3" position={[0.003, 0, 0]}>
                  <group name="Desk003_2" position={[0.002, 0, 0]}>
                    <group name="gray_metal003_1" position={[0.001, 0, 0]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model016" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root001">
            <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
              <group name="ClassRoom+Hall+004_4001" scale={0.001}>
                <group name="Items004_3001" position={[0.003, 0, 0]}>
                  <group name="Desk003_2001" position={[0.002, 0, 0]}>
                    <group name="gray_metal003_1001" position={[0.001, 0, 0]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model017" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode015">
              <group name="SchoolChair" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Wall006" position={[4.671, -6.587, 19.874]}>
          <group name="Left_Angle003" position={[0, 0, -0.152]} />
          <group name="OBJ_PROMPTS001" position={[-0.004, 0, 0.005]} />
          <group name="OBJ_Y003" position={[0, 0, -0.152]} />
        </group>
        <group name="Sketchfab_model018" position={[2.14, -4.886, 5.063]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="adeb93b16b1343ce9259f3bc30ece086fbx002" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode016" />
          </group>
        </group>
        <group name="Sketchfab_model019" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="adeb93b16b1343ce9259f3bc30ece086fbx003" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode017" />
          </group>
        </group>
        <group name="Sketchfab_model020" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx008" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode018">
              <group name="#WIN0003_Frame008" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model021" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx009" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode019">
              <group name="#WIN0003_Frame009" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model022" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx010" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode020">
              <group name="#WIN0003_Frame010" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model023" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx011" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode021">
              <group name="#WIN0003_Frame011" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model024" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx012" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode022">
              <group name="#WIN0003_Frame012" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model025" position={[6.334, -6.587, 19.879]} rotation={[Math.PI / 2, 0, 0]} scale={-1}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx013" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode023">
              <group name="#WIN0003_Frame013" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model026" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="44c15676bd92436aa0e032a2683df647fbx002" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode024">
              <group name="tvCabinet3002" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model027" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="ACfbx005" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode025">
              <group name="AC005" />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model028" position={[4.667, -6.587, 8.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.335, 0.334, 0.402]}>
          <group name="ACfbx006" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode026">
              <group name="AC006" />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model029" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root002">
            <group name="GLTF_SceneRootNode002" rotation={[Math.PI / 2, 0, 0]}>
              <group name="ClassRoom+Hall+004_4002" scale={0.001}>
                <group name="Items004_3002" position={[0.003, 0, 0]}>
                  <group name="Desk003_2002" position={[0.002, 0, 0]}>
                    <group name="gray_metal003_1002" position={[0.001, 0, 0]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model030" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root003">
            <group name="GLTF_SceneRootNode003" rotation={[Math.PI / 2, 0, 0]}>
              <group name="ClassRoom+Hall+004_4003" scale={0.001}>
                <group name="Items004_3003" position={[0.003, 0, 0]}>
                  <group name="Desk003_2003" position={[0.002, 0, 0]}>
                    <group name="gray_metal003_1003" position={[0.001, 0, 0]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model031" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode027">
              <group name="SchoolChair001" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model033" position={[7.358, -6.587, 8.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.335, 0.334, 0.402]}>
          <group name="ACfbx007" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode029">
              <group name="AC007" />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model034" position={[7.358, -6.587, 8.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.335, 0.334, 0.402]}>
          <group name="ACfbx008" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode030">
              <group name="AC008" />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model035" position={[7.358, -6.587, 8.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.335, 0.334, 0.402]}>
          <group name="ACfbx009" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode031">
              <group name="AC009" />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model013" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx002" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode013">
              <group name="SchoolChair002" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Wall002" position={[4.671, -6.587, 19.874]}>
          <group name="Left_Angle001" position={[0, 0, -0.152]} />
          <group name="OBJ_PROMPTS002" position={[-0.004, 0, 0.005]} />
          <group name="OBJ_Y001" position={[0, 0, -0.152]} />
        </group>
        <group name="OBJ_Y004" position={[4.667, -6.587, 19.726]} />
        <group name="Wall008" position={[-9.297, -6.587, 19.877]}>
          <group name="Left_Angle005" position={[0.152, 0, -0.152]} />
          <group name="OBJ_Y005" position={[0, 0, -0.152]} />
        </group>
        <group name="Sketchfab_model048" position={[2.14, -4.886, 5.063]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="adeb93b16b1343ce9259f3bc30ece086fbx004" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode044" />
          </group>
        </group>
        <group name="Sketchfab_model049" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="adeb93b16b1343ce9259f3bc30ece086fbx005" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode045" />
          </group>
        </group>
        <group name="Sketchfab_model050" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx014" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode046">
              <group name="#WIN0003_Frame014" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model051" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx015" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode047">
              <group name="#WIN0003_Frame015" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model052" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx016" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode048">
              <group name="#WIN0003_Frame016" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model053" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx017" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode049">
              <group name="#WIN0003_Frame017" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model054" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx018" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode050">
              <group name="#WIN0003_Frame018" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model055" position={[6.334, -6.587, 19.879]} rotation={[Math.PI / 2, 0, 0]} scale={-1}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx019" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode051">
              <group name="#WIN0003_Frame019" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model056" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="44c15676bd92436aa0e032a2683df647fbx003" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode052">
              <group name="tvCabinet3003" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model057" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="ACfbx010" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode053">
              <group name="AC010" />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model058" position={[4.667, -6.587, 8.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.335, 0.334, 0.402]}>
          <group name="ACfbx011" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode054">
              <group name="AC011">
                <mesh castShadow name="AC_Ac_0008" geometry={nodes.AC_Ac_0008.geometry} material={nodes.AC_Ac_0008.material} position={[-24.459, 29.56, -35.084]} scale={[0.347, 0.266, 0.401]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model059" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root004">
            <group name="GLTF_SceneRootNode004" rotation={[Math.PI / 2, 0, 0]}>
              <group name="ClassRoom+Hall+004_4004" scale={0.001}>
                <group name="Items004_3004" position={[0.003, 0, 0]}>
                  <group name="Desk003_2004" position={[0.002, 0, 0]}>
                    <group name="gray_metal003_1004" position={[0.001, 0, 0]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model060" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root005">
            <group name="GLTF_SceneRootNode005" rotation={[Math.PI / 2, 0, 0]}>
              <group name="ClassRoom+Hall+004_4005" scale={0.001}>
                <group name="Items004_3005" position={[0.003, 0, 0]}>
                  <group name="Desk003_2005" position={[0.002, 0, 0]}>
                    <group name="gray_metal003_1005" position={[0.001, 0, 0]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model061" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx015" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode055">
              <group name="SchoolChair015" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model062" position={[-16.546, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="44c15676bd92436aa0e032a2683df647fbx004" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode056">
              <group name="tvCabinet3004" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow name="tvCabinet3_wood_0006" geometry={nodes.tvCabinet3_wood_0006.geometry} material={materials['Material.167']} position={[0.117, 0.144, 0.08]} rotation={[0, 0, -3.102]} scale={[0.032, 0.007, 0.027]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model063" position={[7.358, -6.587, 8.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.335, 0.334, 0.402]}>
          <group name="ACfbx012" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode057">
              <group name="AC012">
                <mesh castShadow name="AC_Ac_0009" geometry={nodes.AC_Ac_0009.geometry} material={materials['Material.130']} position={[-16.187, 29.56, -35.084]} scale={[0.347, 0.266, 0.401]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model064" position={[7.358, -6.587, 8.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.335, 0.334, 0.402]}>
          <group name="ACfbx013" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode058">
              <group name="AC013">
                <mesh castShadow name="AC_Ac_0010" geometry={nodes.AC_Ac_0010.geometry} material={materials['Material.131']} position={[6.245, 29.56, -35.084]} scale={[0.347, 0.266, 0.401]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model065" position={[7.358, -6.587, 8.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.335, 0.334, 0.402]}>
          <group name="ACfbx014" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode059">
              <group name="AC014">
                <mesh castShadow name="AC_Ac_0011" geometry={nodes.AC_Ac_0011.geometry} material={materials['Material.132']} position={[25.01, 29.56, -35.084]} scale={[0.347, 0.266, 0.401]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model071" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="274d03ff638d453593d5618d775668ebfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode065" />
          </group>
        </group>
        <group name="Sketchfab_model072" position={[6.982, 3.489, 0.55]} rotation={[-Math.PI / 2, 0, 0]} scale={0.647}>
          <group name="88030abe89d54968b87cc2c91d6ccd97fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
            <group name="RootNode066">
              <group name="desk_low" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh castShadow name="desk_low_default_0" geometry={nodes.desk_low_default_0.geometry} material={materials['Material.143']} position={[693.485, 168.132, -174.194]} rotation={[0, 0, 1.602]} scale={[1.103, 1.856, 1.37]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model073" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root006">
            <group name="GLTF_SceneRootNode006" rotation={[Math.PI / 2, 0, 0]}>
              <group name="#TVS0001_Generic_Wide_0">
                <mesh castShadow name="Object_8" geometry={nodes.Object_8.geometry} material={materials.TVS0001_Standby} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model074" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root007">
            <group name="GLTF_SceneRootNode007" rotation={[Math.PI / 2, 0, 0]}>
              <group name="#TVS0001_Generic_Wide_0001">
                <group name="Object_6" position={[14.356, 8.483, -18.824]} rotation={[0, -1.539, 0]} scale={[2.384, 2.611, 1.916]}>
                  <mesh castShadow name="Object_2" geometry={nodes.Object_2.geometry} material={materials['Material.142']} />
                  <mesh castShadow name="Object_2_1" geometry={nodes.Object_2_1.geometry} material={materials['Material.141']} />
                  <mesh castShadow name="Object_2_2" geometry={nodes.Object_2_2.geometry} material={materials['Material.140']} />
                </group>
                <mesh castShadow name="Object_8001" geometry={nodes.Object_8001.geometry} material={materials['TVS0001_Standby.001']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model075" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Circle000" rotation={[0.05, 0, 0]} scale={1.016} />
            <group name="Circle016" rotation={[0.05, 0, 0]}>
              <mesh castShadow name="Circle016_2" geometry={nodes.Circle016_2.geometry} material={materials.Sec_Zeiger} />
              <mesh castShadow name="Circle016_3" geometry={nodes.Circle016_3.geometry} material={materials.min_Zeiger} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model076" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01" />
          </group>
        </group>
        <group name="Sketchfab_model014" position={[7.358, -6.587, 8.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.335, 0.334, 0.402]}>
          <group name="ACfbx002" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode014">
              <group name="AC002" />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model032" position={[7.358, -6.587, 8.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.335, 0.334, 0.402]}>
          <group name="ACfbx003" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode028">
              <group name="AC003" />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model036" position={[7.358, -6.587, 8.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.335, 0.334, 0.402]}>
          <group name="ACfbx004" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode032">
              <group name="AC004" />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model037" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx003" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode033">
              <group name="SchoolChair003" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model038" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx004" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode034">
              <group name="SchoolChair004" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model039" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx005" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode035">
              <group name="SchoolChair005" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model040" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx006" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode036">
              <group name="SchoolChair006" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model041" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx007" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode037">
              <group name="SchoolChair007" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model042" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx008" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode038">
              <group name="SchoolChair008" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model043" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx009" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode039">
              <group name="SchoolChair009" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model044" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx010" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode040">
              <group name="SchoolChair010" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model045" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx011" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode041">
              <group name="SchoolChair011" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model046" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx012" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode042">
              <group name="SchoolChair012" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model047" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx013" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode043">
              <group name="SchoolChair013" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model066" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx014" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode060">
              <group name="SchoolChair014" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model067" position={[-16.579, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="44c15676bd92436aa0e032a2683df647fbx001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode061" />
          </group>
        </group>
        <group name="Sketchfab_model068" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx016" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode062">
              <group name="SchoolChair016" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model069" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx017" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode063">
              <group name="SchoolChair017" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model070" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx018" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode064">
              <group name="SchoolChair018" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model077" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx019" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode067">
              <group name="SchoolChair019" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model078" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e5953a730cbb4503affd601be42f7e80fbx020" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode068">
              <group name="SchoolChair020" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={119} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model079" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01001" />
          </group>
        </group>
        <group name="Sketchfab_model080" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group002" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01002">
              <mesh castShadow name="defaultMaterial002" geometry={nodes.defaultMaterial002.geometry} material={materials['lamp_01.002']} position={[-7.547, 12.889, -21.931]} scale={[0.193, 0.238, 0.207]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model081" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group003" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01003" />
          </group>
        </group>
        <group name="Sketchfab_model082" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group004" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01004">
              <mesh castShadow name="defaultMaterial004" geometry={nodes.defaultMaterial004.geometry} material={materials['lamp_01.004']} position={[-2.66, 12.889, -21.931]} scale={[0.193, 0.238, 0.207]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model083" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group005" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01005">
              <mesh castShadow name="defaultMaterial005" geometry={nodes.defaultMaterial005.geometry} material={materials['lamp_01.005']} position={[6.751, 12.889, -21.931]} scale={[0.193, 0.238, 0.207]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model084" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group006" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01006" />
          </group>
        </group>
        <group name="Sketchfab_model085" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group007" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01007">
              <mesh castShadow name="defaultMaterial007" geometry={nodes.defaultMaterial007.geometry} material={materials['lamp_01.007']} position={[12.201, 12.889, -21.931]} scale={[0.193, 0.238, 0.207]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model086" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group008" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01008">
              <mesh castShadow name="defaultMaterial008" geometry={nodes.defaultMaterial008.geometry} material={materials['lamp_01.008']} position={[6.754, 12.889, -15.908]} scale={[0.193, 0.238, 0.207]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model087" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group009" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01009">
              <mesh castShadow name="defaultMaterial009" geometry={nodes.defaultMaterial009.geometry} material={materials['lamp_01.009']} position={[12.201, 12.889, -15.908]} scale={[0.193, 0.238, 0.207]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model088" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group010" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01010" />
          </group>
        </group>
        <group name="Sketchfab_model089" position={[4.667, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group011" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01011">
              <mesh castShadow name="defaultMaterial011" geometry={nodes.defaultMaterial011.geometry} material={materials['lamp_01.011']} position={[-7.547, 12.889, -16.021]} scale={[0.193, 0.238, 0.207]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model091" position={[-4.154, 4.575, 5.47]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.74, 1, 0.5]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx020" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode069">
              <group name="#WIN0003_Frame020" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="#WIN0003_Window" position={[0.441, -0.039, 0.082]}>
                  <group name="#WIN0003_Handle" position={[-0.84, -0.018, 0.55]}>
                    <mesh castShadow name="#WIN0003_Handle_#WIN0003_Textures_0" geometry={nodes['#WIN0003_Handle_#WIN0003_Textures_0'].geometry} material={materials.WIN0003_Textures} />
                  </group>
                  <mesh castShadow name="#WIN0003_Window_#WIN0003_Textures_0" geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0'].geometry} material={materials.WIN0003_Textures} />
                </group>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0'].geometry} material={materials.WIN0003_Textures} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model008" position={[5.208, 2.767, 0.226]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx006" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode008">
              <group name="#WIN0003_Frame006" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0011" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0011'].geometry} material={materials['Material.031']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0012" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0012'].geometry} material={materials['Material.040']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0013" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0013'].geometry} material={materials['Material.004']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0014" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0014'].geometry} material={materials['Material.036']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model005" position={[5.208, 3.863, 0.226]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx003" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode005">
              <group name="#WIN0003_Frame003" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="#WIN0003_Frame_#WIN0003_Textures_0313" position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]}>
                  <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0313_1" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0313_1'].geometry} material={materials['Material.033']} />
                  <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0313_2" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0313_2'].geometry} material={materials['Material.001']} />
                </group>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0316" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0316'].geometry} material={materials['Material.007']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0317" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0317'].geometry} material={materials['Material.007']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0318" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0318'].geometry} material={materials['Material.007']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0319" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0319'].geometry} material={materials.Glass} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0320" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0320'].geometry} material={materials.Glass} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0321" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0321'].geometry} material={materials.Glass} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0346" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0346'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0358" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0358'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0410" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0410'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0443" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0443'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0447" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0447'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0448" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0448'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0454" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0454'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0482" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0482'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0486" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0486'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0487" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0487'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0493" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0493'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0518" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0518'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0521" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0521'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0522" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0522'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0523" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0523'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0525" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0525'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0527" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0527'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0531" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0531'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0534" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0534'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0538" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0538'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0541" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0541'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0545" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0545'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0548" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0548'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0552" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0552'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0567" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0567'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0624" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0624'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0683" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0683'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0740" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0740'].geometry} material={materials.Metal} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0820" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0820'].geometry} material={materials.Glass} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0834" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0834'].geometry} material={materials.Glass} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0835" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0835'].geometry} material={materials.Glass} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0838" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0838'].geometry} material={materials.Glass} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0843" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0843'].geometry} material={materials.Glass} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0846" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0846'].geometry} material={materials.Glass} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0855" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0855'].geometry} material={materials['Material.007']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0856" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0856'].geometry} material={materials['Material.008']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0857" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0857'].geometry} material={materials['Material.005']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0859" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0859'].geometry} material={materials['Material.009']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0860" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0860'].geometry} material={materials['Material.041']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0861" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0861'].geometry} material={materials['Material.013']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0864" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0864'].geometry} material={materials['Material.009']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0866" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0866'].geometry} material={materials['Material.039']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0867" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0867'].geometry} material={materials['Material.005']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0868" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0868'].geometry} material={materials['Material.043']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model090" position={[9.536, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group012" rotation={[Math.PI / 2, 0, 0]}>
            <group name="lamp_01012">
              <mesh castShadow name="defaultMaterial001" geometry={nodes.defaultMaterial001.geometry} material={materials['lamp_01.001']} position={[-7.547, 12.889, -16.021]} scale={[0.193, 0.238, 0.207]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model092" position={[-3.134, 4.575, 5.47]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.74, 1, 0.5]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx021" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode070">
              <group name="#WIN0003_Frame021" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="#WIN0003_Window001" position={[0.441, -0.039, 0.082]}>
                  <group name="#WIN0003_Handle001" position={[-0.84, -0.018, 0.55]}>
                    <mesh castShadow name="#WIN0003_Handle_#WIN0003_Textures_0001" geometry={nodes['#WIN0003_Handle_#WIN0003_Textures_0001'].geometry} material={materials['WIN0003_Textures.029']} />
                  </group>
                  <mesh castShadow name="#WIN0003_Window_#WIN0003_Textures_0001" geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0001'].geometry} material={materials['WIN0003_Textures.029']} />
                </group>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0001" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0001'].geometry} material={materials['WIN0003_Textures.029']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model093" position={[-5.495, 4.575, 5.47]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.74, 1, 0.5]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx022" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode071">
              <group name="#WIN0003_Frame022" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="#WIN0003_Window002" position={[0.441, -0.039, 0.082]}>
                  <group name="#WIN0003_Handle002" position={[-0.84, -0.018, 0.55]}>
                    <mesh castShadow name="#WIN0003_Handle_#WIN0003_Textures_0002" geometry={nodes['#WIN0003_Handle_#WIN0003_Textures_0002'].geometry} material={materials['WIN0003_Textures.030']} />
                  </group>
                  <mesh castShadow name="#WIN0003_Window_#WIN0003_Textures_0002" geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0002'].geometry} material={materials['WIN0003_Textures.030']} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model094" position={[-6.624, 4.575, 5.47]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.74, 1, 0.5]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx023" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode072">
              <group name="#WIN0003_Frame023" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0009" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0009'].geometry} material={materials['WIN0003_Textures.031']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model095" position={[18.562, 4.575, 5.721]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.74, -1, -0.5]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx024" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode073">
              <group name="#WIN0003_Frame024" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0043" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0043'].geometry} material={materials['WIN0003_Textures.039']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model096" position={[17.432, 4.575, 5.721]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.74, -1, -0.5]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx025" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode074">
              <group name="#WIN0003_Frame025" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="#WIN0003_Window003" position={[0.441, -0.039, 0.082]}>
                  <mesh castShadow name="#WIN0003_Window_#WIN0003_Textures_0003" geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0003'].geometry} material={materials['WIN0003_Textures.032']} />
                </group>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0045" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0045'].geometry} material={materials['WIN0003_Textures.032']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model097" position={[15.072, 4.575, 5.721]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.74, -1, -0.5]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx026" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode075">
              <group name="#WIN0003_Frame026" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="#WIN0003_Window004" position={[0.441, -0.039, 0.082]}>
                  <mesh castShadow name="#WIN0003_Window_#WIN0003_Textures_0004" geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0004'].geometry} material={materials['WIN0003_Textures.033']} />
                </group>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0046" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0046'].geometry} material={materials['WIN0003_Textures.033']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model098" position={[16.092, 4.575, 5.721]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.74, -1, -0.5]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx027" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode076">
              <group name="#WIN0003_Frame027" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="#WIN0003_Window005" position={[0.441, -0.039, 0.082]}>
                  <mesh castShadow name="#WIN0003_Window_#WIN0003_Textures_0005" geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0005'].geometry} material={materials['WIN0003_Textures.034']} />
                </group>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0047" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0047'].geometry} material={materials['WIN0003_Textures.034']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model099" position={[6.73, 2.767, 0.477]} rotation={[Math.PI / 2, 0, 0]} scale={-1}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx028" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode077">
              <group name="#WIN0003_Frame028" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0035" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0035'].geometry} material={materials['Material.021']} position={[-9.411, -5.192, 0.654]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0040" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0040'].geometry} material={materials['Material.113']} position={[-9.411, -5.192, 0.65]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0041" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0041'].geometry} material={materials['Material.021']} position={[-9.411, -5.192, 0.645]} scale={[1, 1, 0.704]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model100" position={[6.73, 3.863, 0.477]} rotation={[Math.PI / 2, 0, 0]} scale={-1}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx029" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode078">
              <group name="#WIN0003_Frame029" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0010" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0010'].geometry} material={materials['Material.107']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0015" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0015'].geometry} material={materials['Material.108']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0016" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0016'].geometry} material={materials['Material.021']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0017" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0017'].geometry} material={materials['Material.109']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0019" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0019'].geometry} material={materials['Material.110']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0021" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0021'].geometry} material={materials['Material.019']} position={[-9.422, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0022" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0022'].geometry} material={materials['Material.020']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0023" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0023'].geometry} material={materials['Material.108']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0024" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0024'].geometry} material={materials['Material.112']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0025" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0025'].geometry} material={materials['Material.111']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0026" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0026'].geometry} material={materials['Glass.042']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0027" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0027'].geometry} material={materials['Glass.042']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0028" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0028'].geometry} material={materials['Glass.042']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0029" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0029'].geometry} material={materials['Material.111']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0030" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0030'].geometry} material={materials['Material.111']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0031" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0031'].geometry} material={materials['Material.111']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0034" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0034'].geometry} material={materials['Material.030']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model101" position={[-2.32, -6.587, 19.879]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="44c15676bd92436aa0e032a2683df647fbx005" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode079">
              <group name="tvCabinet3001" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow name="tvCabinet3_wood_0004" geometry={nodes.tvCabinet3_wood_0004.geometry} material={materials['Material.166']} position={[0.191, 0.144, 0.08]} rotation={[0, 0, -3.102]} scale={[0.032, 0.011, 0.027]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model102" position={[14.943, 3.863, 0.226]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx030" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode080">
              <group name="#WIN0003_Frame030" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0048" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0048'].geometry} material={materials['Glass.047']} position={[-9.411, -5.392, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0049" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0049'].geometry} material={materials['Glass.047']} position={[-9.411, -5.392, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0050" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0050'].geometry} material={materials['Metal.008']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0052" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0052'].geometry} material={materials['Metal.008']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0053" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0053'].geometry} material={materials['Metal.008']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0054" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0054'].geometry} material={materials['Metal.008']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0059" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0059'].geometry} material={materials['Metal.008']} position={[-9.411, -5.432, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0060" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0060'].geometry} material={materials['Metal.008']} position={[-9.411, -5.432, 0.685]} scale={[1, 1, 0.704]} />
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0062" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0062'].geometry} material={materials['Metal.008']} position={[-9.411, -5.192, 0.685]} scale={[1, 1, 0.704]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model103" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="274d03ff638d453593d5618d775668ebfbx001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode081">
              <group name="Box01" position={[7.49, 34.373, -108.052]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Box02" position={[-51.39, 55.287, -133.687]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Circle01" position={[-29.262, 24.564, -81.484]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder01" position={[-21.91, 2.302, -108.052]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder03" position={[-14.457, 23.805, -108.052]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder07" position={[-18.739, 27.145, -126.39]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder08" position={[-12.851, 27.386, -126.404]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder09" position={[-12.9, 28.287, -131.49]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder10" position={[-18.788, 28.046, -131.476]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh castShadow name="Cylinder10_BlackMetal_0" geometry={nodes.Cylinder10_BlackMetal_0.geometry} material={materials['Material.144']} position={[37.529, -129.432, -26.902]} rotation={[0, 0, 3.099]} scale={[0.014, 0.014, 0.013]} />
              </group>
              <group name="Cylinder11" position={[-18.777, 27.845, -84.724]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder12" position={[-18.728, 26.944, -89.81]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder13" position={[-12.889, 28.086, -84.71]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder14" position={[-12.84, 27.185, -89.796]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder15" position={[-19.862, 33.508, -79.262]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder16" position={[-12.681, 33.814, -79.195]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder17" position={[-12.681, 33.814, -136.427]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Cylinder18" position={[-19.862, 33.508, -136.361]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Line01" position={[-25.15, 24.272, -108.052]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Line02" position={[-25.595, 24.171, -86.278]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Line04" position={[-18.111, 48.52, -79.051]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Line05" position={[-18.111, 48.52, -136.572]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Rectangle02" position={[-21.91, -0.065, -108.052]} rotation={[-Math.PI / 2, 0, 0]}>
                <group name="Cylinder04" position={[-9.737, 28.277, -4.174]}>
                  <group name="Cylinder02" position={[-1.576, 0.248, -4.729]} />
                </group>
                <group name="Cylinder20" position={[23.84, 17.931, -4.174]}>
                  <group name="Cylinder19" position={[-0.419, 1.539, -4.729]} />
                </group>
                <group name="Cylinder21" position={[24.416, -17.128, -4.174]}>
                  <group name="Cylinder22" position={[0.917, 1.305, -4.729]} />
                </group>
                <group name="Cylinder23" position={[-8.754, -28.449, -4.174]}>
                  <group name="Cylinder24" position={[1.58, -0.216, -4.729]} />
                </group>
                <group name="Cylinder26" position={[-29.848, -0.519, -4.174]}>
                  <group name="Cylinder25" position={[-0.697, 1.434, -4.729]} />
                </group>
              </group>
              <group name="Rectangle11" position={[-16.035, 30.479, -108.052]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model104" position={[0, 3.112, -0.005]} rotation={[-Math.PI / 2, 0, -3.142]} scale={[0.428, 1, 0.394]}>
          <group name="root008">
            <group name="GLTF_SceneRootNode008" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sec_31" position={[0, 0, 0.015]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.422, 0.005, 0.031]} />
            </group>
          </group>
        </group>
        <group name="22_0" position={[0, -0.738, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.009, -0.293, -0.009]} />
        <group name="glass_1" position={[0, -1.515, 0]} rotation={[Math.PI, 0, 0]} />
        <group name="t_2" position={[0, -0.65, -0.915]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="t013_15" position={[0, -0.65, 0.797]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="t014_16" position={[0.804, -0.65, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="t015_17" position={[-0.836, -0.65, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="t016_18" position={[-0.722, -0.65, 0.418]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="t017_19" position={[0, -0.65, -0.797]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="t018_20" position={[-0.417, -0.65, 0.723]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="t019_21" position={[-0.397, -0.65, -0.693]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="t020_22" position={[-0.688, -0.65, -0.401]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="t021_23" position={[0.396, -0.65, -0.693]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="t022_24" position={[0.687, -0.65, -0.402]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="t023_25" position={[0.669, -0.65, 0.381]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="t024_26" position={[0, -0.65, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.073, 0.728, 0.073]} />
        <group name="t025_27" position={[0.391, -0.65, 0.657]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.238, 2.365, 0.238]} />
        <group name="Sketchfab_model105" position={[-0.924, 5.935, -3.69]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.518, 1, 1.499]}>
          <group name="3591266375494020b52a9bf77f651d47fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode082">
              <group name="WallClock3" rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
                <mesh castShadow name="WallClock3_WallClock3_0" geometry={nodes.WallClock3_WallClock3_0.geometry} material={materials.WallClock3} position={[359.382, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model106" position={[-0.924, 5.935, -3.69]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.518, 1, 1.499]}>
          <group name="3591266375494020b52a9bf77f651d47fbx001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode083">
              <group name="WallClock3001" rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
                <mesh castShadow name="WallClock3_WallClock3_0001" geometry={nodes.WallClock3_WallClock3_0001.geometry} material={materials['WallClock3.001']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model107" position={[6.73, 2.767, 0.477]} rotation={[Math.PI / 2, 0, 0]} scale={-1}>
          <group name="#WIN0003_Residential_Plastic_White_142x62x104fbx031" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode084">
              <group name="#WIN0003_Frame031" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh castShadow name="#WIN0003_Frame_#WIN0003_Textures_0002" geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0002'].geometry} material={materials['Material.023']} position={[-10.716, -5.192, 0.65]} scale={[1, 1, 0.704]} />
              </group>
            </group>
          </group>
        </group>
        <mesh castShadow name="Roller_bottom" geometry={nodes.Roller_bottom.geometry} material={materials['Material.014']} position={[12.4, -2.892, 7.473]} />
        <mesh castShadow name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Material.046']} position={[-2.942, 6.415, 4.003]} scale={[0.4, 0.05, 0.6]} />
        <mesh castShadow name="Cube023" geometry={nodes.Cube023.geometry} material={nodes.Cube023.material} position={[1.998, 6.405, -2.147]} scale={[0.4, 0.05, 0.6]} />
        <mesh castShadow name="Cube030" geometry={nodes.Cube030.geometry} material={nodes.Cube030.material} position={[-2.942, 6.425, -2.147]} scale={[0.4, 0.05, 0.6]} />
        <mesh castShadow name="Roller_bottom001" geometry={nodes.Roller_bottom001.geometry} material={materials['Material.015']} position={[12.4, -2.892, 7.473]} />
        <mesh castShadow name="Cube038" geometry={nodes.Cube038.geometry} material={materials['Material.002']} position={[-7.698, 3.611, -3.75]} rotation={[0, 1.571, 0]} scale={[0.3, 3, 0.25]} />
        <mesh castShadow name="Cube031" geometry={nodes.Cube031.geometry} material={materials['Material.128']} position={[12.917, 5.955, -3.814]} rotation={[0, 0, -Math.PI / 2]} scale={[0.45, 6.66, 0.1]} />
        <mesh castShadow name="Plane003" geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[-2.902, 5.416, 5.82]} rotation={[Math.PI / 2, 0, 0]} scale={[0.75, 1, 0.95]} />
        <mesh castShadow name="Cube049" geometry={nodes.Cube049.geometry} material={materials['Material.029']} position={[19.479, 2.385, -1.824]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.05, -1.66, -0.05]} />
        <mesh castShadow name="Roller_bottom002" geometry={nodes.Roller_bottom002.geometry} material={materials['Material.017']} position={[12.4, -2.892, 7.473]} />
        <mesh castShadow name="Cube037" geometry={nodes.Cube037.geometry} material={materials['Glass.017']} position={[-7.659, 3.975, -1.671]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1.65, 1.8, 0.05]} />
        <mesh castShadow name="Cube039" geometry={nodes.Cube039.geometry} material={materials['Glass.018']} position={[-7.659, 3.975, 3.527]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1.65, 1.8, 0.05]} />
        <mesh castShadow name="Cube053" geometry={nodes.Cube053.geometry} material={materials['Material.016']} position={[5.937, 3.649, 5.93]} scale={[14.025, 3, 0.076]} />
        <mesh castShadow name="Cube063" geometry={nodes.Cube063.geometry} material={materials['Material.164']} position={[-5.374, 6.974, 0.898]} scale={[0.2, 0.5, 4.975]} />
        <mesh castShadow name="Cube066" geometry={nodes.Cube066.geometry} material={nodes.Cube066.material} position={[-2.942, 6.415, 4.003]} scale={[0.4, 0.05, 0.6]} />
        <mesh castShadow name="Cube067" geometry={nodes.Cube067.geometry} material={nodes.Cube067.material} position={[1.998, 6.405, -2.147]} scale={[0.4, 0.05, 0.6]} />
        <mesh castShadow name="Cube068" geometry={nodes.Cube068.geometry} material={materials['Material.048']} position={[-2.942, 6.425, -2.147]} scale={[0.4, 0.05, 0.6]} />
        <mesh castShadow name="Roller_bottom003" geometry={nodes.Roller_bottom003.geometry} material={materials['Material.018']} position={[12.4, -2.892, 7.473]} />
        <mesh castShadow name="Cube075" geometry={nodes.Cube075.geometry} material={nodes.Cube075.material} position={[12.917, 5.955, -3.814]} rotation={[0, 0, -Math.PI / 2]} scale={[0.45, 6.66, 0.1]} />
        <mesh castShadow name="Plane006" geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} position={[-2.902, 5.416, 5.82]} rotation={[Math.PI / 2, 0, 0]} scale={[0.75, 1, 0.95]} />
        <mesh castShadow name="tvCabinet3_wood_0003" geometry={nodes.tvCabinet3_wood_0003.geometry} material={materials['wood.003']} position={[4.784, -2.797, 22.731]} rotation={[0, 0, -3.102]} scale={[0.028, 0.018, 0.022]} />
        <mesh castShadow name="Roller_bottom004" geometry={nodes.Roller_bottom004.geometry} material={materials['Material.022']} position={[12.4, -2.892, 7.473]} />
        <mesh castShadow name="Cube089" geometry={nodes.Cube089.geometry} material={materials['Material.076']} position={[-7.688, 3.551, 5.56]} rotation={[0, 1.571, 0]} scale={[0.3, 3, 0.25]} />
        <mesh castShadow name="Cube090" geometry={nodes.Cube090.geometry} material={materials['Glass.029']} position={[-7.659, 3.975, -1.671]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1.65, 1.8, 0.05]} />
        <mesh castShadow name="Cube091" geometry={nodes.Cube091.geometry} material={materials['Glass.030']} position={[-7.659, 3.975, 3.527]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1.65, 1.8, 0.05]} />
        <mesh castShadow name="Cube092" geometry={nodes.Cube092.geometry} material={materials['Material.165']} position={[-7.604, 6.934, 0.898]} scale={[0.2, 0.5, 4.975]} />
        <mesh castShadow name="Cube093" geometry={nodes.Cube093.geometry} material={materials['Material.155']} position={[17.086, 6.974, 0.898]} scale={[0.2, 0.5, 4.975]} />
        <mesh castShadow name="Cube094" geometry={nodes.Cube094.geometry} material={materials['Material.157']} position={[12.216, 6.974, 0.898]} scale={[0.2, 0.5, 4.975]} />
        <mesh castShadow name="Cube095" geometry={nodes.Cube095.geometry} material={materials['Material.159']} position={[7.566, 6.974, 0.898]} scale={[0.2, 0.5, 4.975]} />
        <mesh castShadow name="Cube096" geometry={nodes.Cube096.geometry} material={materials['Material.006']} position={[-8.023, 3.636, 0.975]} rotation={[0, 1.571, 0]} scale={[5.025, 3, 0.076]} />
        <mesh castShadow name="Cube097" geometry={nodes.Cube097.geometry} material={nodes.Cube097.material} position={[5.937, 3.649, 5.93]} scale={[14.025, 3, 0.076]} />
        <mesh castShadow name="Cube098" geometry={nodes.Cube098.geometry} material={materials['Material.011']} position={[5.937, 3.629, -3.95]} scale={[14.025, 3, 0.076]} />
        <mesh castShadow name="Cube099" geometry={nodes.Cube099.geometry} material={materials['Material.012']} position={[19.937, 3.646, 0.975]} rotation={[0, 1.571, 0]} scale={[5.025, 3, 0.076]} />
        <mesh castShadow name="Cube100" geometry={nodes.Cube100.geometry} material={materials['Material.158']} position={[9.876, 6.974, 0.898]} scale={[0.2, 0.5, 4.975]} />
        <mesh castShadow name="Cube101" geometry={nodes.Cube101.geometry} material={materials['Material.156']} position={[14.586, 6.974, 0.898]} scale={[0.2, 0.5, 4.975]} />
        <mesh castShadow name="Cube103" geometry={nodes.Cube103.geometry} material={materials['Material.154']} position={[19.686, 6.974, 0.898]} scale={[0.2, 0.5, 4.975]} />
        <mesh castShadow name="Cube104" geometry={nodes.Cube104.geometry} material={materials['Material.161']} position={[1.966, 6.974, 0.898]} scale={[0.2, 0.5, 4.975]} />
        <mesh castShadow name="Cube105" geometry={nodes.Cube105.geometry} material={materials['Material.162']} position={[-0.504, 6.974, 0.898]} scale={[0.2, 0.5, 4.975]} />
        <mesh castShadow name="Cube106" geometry={nodes.Cube106.geometry} material={materials['Material.164']} position={[-2.974, 6.974, 0.898]} scale={[0.2, 0.5, 4.975]} />
        <mesh castShadow name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.151']} position={[5.819, 7.467, 2.403]} scale={[14.65, 1, 7.7]} />
        <mesh castShadow name="Cube108" geometry={nodes.Cube108.geometry} material={materials['Material.050']} position={[12.924, 6.413, -3.395]} scale={[6.561, 0.05, 0.65]} />
        <mesh castShadow name="Cube109" geometry={nodes.Cube109.geometry} material={materials['Material.044']} position={[1.998, 6.375, 3.993]} scale={[0.4, 0.05, 0.6]} />
        <mesh castShadow name="Cube110" geometry={nodes.Cube110.geometry} material={nodes.Cube110.material} position={[-2.942, 6.415, 4.003]} scale={[0.4, 0.05, 0.6]} />
        <mesh castShadow name="Cube111" geometry={nodes.Cube111.geometry} material={nodes.Cube111.material} position={[1.998, 6.405, -2.147]} scale={[0.4, 0.05, 0.6]} />
        <mesh castShadow name="Cube112" geometry={nodes.Cube112.geometry} material={nodes.Cube112.material} position={[-2.942, 6.425, -2.147]} scale={[0.4, 0.05, 0.6]} />
        <mesh castShadow name="Roller_bottom005" geometry={nodes.Roller_bottom005.geometry} material={materials['Material.024']} position={[12.4, -2.892, 7.473]} />
        <mesh castShadow name="Cube113" geometry={nodes.Cube113.geometry} material={materials['Material.035']} position={[-1.075, 6.413, -3.404]} scale={[6.6, 0.05, 0.65]} />
        <mesh castShadow name="Cube114" geometry={nodes.Cube114.geometry} material={materials['Material.136']} position={[-1.565, 6.413, 5.226]} scale={[5.9, 0.05, 0.65]} />
        <mesh castShadow name="Cube115" geometry={nodes.Cube115.geometry} material={materials['Material.029']} position={[-1.634, 6.444, 0.978]} scale={[5.9, 0.05, 1.2]} />
        <mesh castShadow name="Plane008" geometry={nodes.Plane008.geometry} material={materials['Material.145']} position={[5.819, 0.637, 2.403]} scale={[14.65, 1, 7.7]} />
        <mesh castShadow name="Cube116" geometry={nodes.Cube116.geometry} material={materials['Material.160']} position={[4.506, 6.974, 0.898]} scale={[0.2, 0.5, 4.975]} />
        <mesh castShadow name="Cube117" geometry={nodes.Cube117.geometry} material={materials['Material.076']} position={[-7.698, 3.611, -3.75]} rotation={[0, 1.571, 0]} scale={[0.3, 3, 0.25]} />
        <mesh castShadow name="Cube118" geometry={nodes.Cube118.geometry} material={materials['Material.114']} position={[5.952, 4.091, -3.47]} rotation={[0, 1.571, 0]} scale={[0.45, 3.4, 0.45]} />
        <mesh castShadow name="Cube119" geometry={nodes.Cube119.geometry} material={nodes.Cube119.material} position={[12.917, 5.955, -3.814]} rotation={[0, 0, -Math.PI / 2]} scale={[0.45, 6.66, 0.1]} />
        <mesh castShadow name="Cube120" geometry={nodes.Cube120.geometry} material={materials['Material.127']} position={[-7.643, 5.955, -2.114]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.45, 1.91, 0.05]} />
        <mesh castShadow name="Plane009" geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} position={[-2.902, 5.416, 5.82]} rotation={[Math.PI / 2, 0, 0]} scale={[0.75, 1, 0.95]} />
        <mesh castShadow name="Cube121" geometry={nodes.Cube121.geometry} material={materials['Material.078']} position={[12.857, 2.385, -3.794]} rotation={[0, 0, -Math.PI / 2]} scale={[0.05, 6.51, 0.05]} />
        <mesh castShadow name="Cube122" geometry={nodes.Cube122.geometry} material={materials['Material.148']} position={[-7.633, 5.955, 4.096]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.45, 1.91, 0.05]} />
        <mesh castShadow name="Cube123" geometry={nodes.Cube123.geometry} material={materials['Material.089']} position={[-7.533, 2.405, 3.746]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.05, 1.56, 0.05]} />
        <mesh castShadow name="Cube124" geometry={nodes.Cube124.geometry} material={materials['Material.090']} position={[-7.533, 2.385, -1.874]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.05, 1.66, 0.05]} />
        <mesh castShadow name="Cube125" geometry={nodes.Cube125.geometry} material={materials['Material.091']} position={[-1.093, 2.385, -3.794]} rotation={[0, 0, -Math.PI / 2]} scale={[0.05, 6.51, 0.05]} />
        <mesh castShadow name="Cube126" geometry={nodes.Cube126.geometry} material={materials['Material.150']} position={[19.439, 5.955, 4.096]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.45, -1.91, -0.05]} />
        <group name="Cube127" position={[19.594, 3.975, -1.521]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-1.65, -1.8, -0.05]}>
          <mesh castShadow name="Cube127_1" geometry={nodes.Cube127_1.geometry} material={materials['Glass.034']} />
          <mesh castShadow name="Cube127_2" geometry={nodes.Cube127_2.geometry} material={materials['Glass.035']} />
        </group>
        <mesh castShadow name="Cube128" geometry={nodes.Cube128.geometry} material={materials['Material.150']} position={[19.449, 5.955, -2.114]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.45, -1.91, -0.05]} />
        <mesh castShadow name="Cube130" geometry={nodes.Cube130.geometry} material={materials['Material.093']} position={[19.603, 3.541, 5.56]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[-0.3, -3, -0.25]} />
        <mesh castShadow name="Cube131" geometry={nodes.Cube131.geometry} material={materials['Material.094']} position={[19.479, 2.385, 3.856]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.05, -1.66, -0.05]} />
        <mesh castShadow name="Cube132" geometry={nodes.Cube132.geometry} material={materials['Material.127']} position={[-1.113, 5.955, -3.814]} rotation={[0, 0, -Math.PI / 2]} scale={[0.45, 6.66, 0.1]} />
        <group name="Roller" position={[2.6, 5.405, -3.756]} scale={[2.378, 1.714, 1]}>
          <mesh castShadow name="Roller_1" geometry={nodes.Roller_1.geometry} material={nodes.Roller_1.material} />
          <mesh castShadow name="Roller_2" geometry={nodes.Roller_2.geometry} material={materials['Material.118']} />
          <mesh castShadow name="SideL" geometry={nodes.SideL.geometry} material={materials['Plastic_roller_material.003']} position={[0.026, 0, 0]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh castShadow name="SideR" geometry={nodes.SideR.geometry} material={materials['Plastic_roller_material.003']} position={[0.974, 0, 0]} />
          <mesh castShadow name="String" geometry={nodes.String.geometry} material={materials.String_material} position={[1.015, -0.38, 0]} />
        </group>
        <mesh castShadow name="Roller_bottom006" geometry={nodes.Roller_bottom006.geometry} material={materials['Material.025']} position={[4.667, -8.287, 19.879]} />
        <group name="Cylinder18_BlackMetal_0" position={[34.375, -113.453, -22.757]} rotation={[0, 0, -3.11]} scale={[0.015, 0.015, 0.012]}>
          <mesh castShadow name="Cylinder18_BlackMetal_0_1" geometry={nodes.Cylinder18_BlackMetal_0_1.geometry} material={materials.BlackMetal} />
          <mesh castShadow name="Cylinder18_BlackMetal_0_2" geometry={nodes.Cylinder18_BlackMetal_0_2.geometry} material={materials.Matteplastic} />
          <mesh castShadow name="Cylinder18_BlackMetal_0_3" geometry={nodes.Cylinder18_BlackMetal_0_3.geometry} material={materials.Lether} />
          <mesh castShadow name="Cylinder18_BlackMetal_0_4" geometry={nodes.Cylinder18_BlackMetal_0_4.geometry} material={materials.Chairback} />
          <mesh castShadow name="Cylinder18_BlackMetal_0_5" geometry={nodes.Cylinder18_BlackMetal_0_5.geometry} material={materials.Chrome} />
        </group>
        <mesh castShadow name="tvCabinet3_wood_0001" geometry={nodes.tvCabinet3_wood_0001.geometry} material={materials['wood.001']} position={[4.784, -2.797, 22.731]} rotation={[0, 0, -3.102]} scale={[0.028, 0.018, 0.022]} />
        <group name="Roller001" position={[-6.972, 5.405, -3.756]} scale={[2.378, 1.714, 1]}>
          <mesh castShadow name="Roller001_1" geometry={nodes.Roller001_1.geometry} material={nodes.Roller001_1.material} />
          <mesh castShadow name="Roller001_2" geometry={nodes.Roller001_2.geometry} material={materials['Material.124']} />
        </group>
        <group name="Roller002" position={[-3.742, 5.405, -3.756]} scale={[2.378, 1.714, 1]}>
          <mesh castShadow name="Roller002_1" geometry={nodes.Roller002_1.geometry} material={nodes.Roller002_1.material} />
          <mesh castShadow name="Roller002_2" geometry={nodes.Roller002_2.geometry} material={materials['Material.123']} />
        </group>
        <group name="Roller003" position={[-0.509, 5.405, -3.756]} scale={[2.378, 1.714, 1]}>
          <mesh castShadow name="Roller003_1" geometry={nodes.Roller003_1.geometry} material={nodes.Roller003_1.material} />
          <mesh castShadow name="Roller003_2" geometry={nodes.Roller003_2.geometry} material={materials['Material.122']} />
        </group>
        <group name="Roller004" position={[6.75, 5.417, -3.755]} scale={[2.378, 1.714, 1]}>
          <mesh castShadow name="Roller004_1" geometry={nodes.Roller004_1.geometry} material={nodes.Roller004_1.material} />
          <mesh castShadow name="Roller004_2" geometry={nodes.Roller004_2.geometry} material={materials['Material.125']} />
        </group>
        <group name="Roller005" position={[10.058, 5.405, -3.756]} scale={[2.378, 1.714, 1]}>
          <mesh castShadow name="Roller005_1" geometry={nodes.Roller005_1.geometry} material={materials['Material.126']} />
          <mesh castShadow name="Roller005_2" geometry={nodes.Roller005_2.geometry} material={nodes.Roller005_2.material} />
        </group>
        <group name="Roller006" position={[16.544, 5.405, -3.756]} scale={[2.378, 1.714, 1]}>
          <mesh castShadow name="Roller006_1" geometry={nodes.Roller006_1.geometry} material={nodes.Roller006_1.material} />
          <mesh castShadow name="Roller006_2" geometry={nodes.Roller006_2.geometry} material={materials['Material.003']} />
        </group>
        <group name="Roller007" position={[13.513, 5.405, -3.756]} scale={[2.378, 1.714, 1]}>
          <mesh castShadow name="Roller007_1" geometry={nodes.Roller007_1.geometry} material={nodes.Roller007_1.material} />
          <mesh castShadow name="Roller007_2" geometry={nodes.Roller007_2.geometry} material={materials['Material.010']} />
        </group>
        <mesh castShadow name="Plane010" geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} position={[-7.432, 5.918, 0.949]} rotation={[0, 0, 1.56]} scale={[0.48, 1, 0.142]} />
        <mesh castShadow name="Plane011" geometry={nodes.Plane011.geometry} material={nodes.Plane011.material} position={[-7.432, 5.918, 0.226]} rotation={[0, 0, 1.56]} scale={[0.48, 1, 0.142]} />
        <mesh castShadow name="Plane012" geometry={nodes.Plane012.geometry} material={nodes.Plane012.material} position={[-7.432, 5.918, 1.651]} rotation={[0, 0, 1.56]} scale={[0.48, 1, 0.142]} />
        <mesh castShadow name="Plane013" geometry={nodes.Plane013.geometry} material={nodes.Plane013.material} position={[19.34, 5.918, 1.723]} rotation={[0, 0, 1.56]} scale={[0.48, 1, 0.142]} />
        <mesh castShadow name="Plane014" geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} position={[19.34, 5.918, 0.226]} rotation={[0, 0, 1.56]} scale={[0.48, 1, 0.142]} />
        <mesh castShadow name="Plane015" geometry={nodes.Plane015.geometry} material={nodes.Plane015.material} position={[19.34, 5.918, 1.017]} rotation={[0, 0, 1.56]} scale={[0.48, 1, 0.142]} />
        <mesh castShadow name="Plane016" geometry={nodes.Plane016.geometry} material={nodes.Plane016.material} position={[17.246, 6.379, 1.716]} rotation={[0, 0, -0.003]} scale={[2.131, 1, 0.142]} />
        <mesh castShadow name="Plane017" geometry={nodes.Plane017.geometry} material={nodes.Plane017.material} position={[17.696, 6.379, 0.221]} rotation={[0, 0, -0.003]} scale={[1.672, 1, 0.142]} />
        <mesh castShadow name="Plane018" geometry={nodes.Plane018.geometry} material={nodes.Plane018.material} position={[18.052, 6.379, 1.008]} rotation={[0, 0, -0.003]} scale={[1.308, 1, 0.142]} />
        <mesh castShadow name="Plane020" geometry={nodes.Plane020.geometry} material={nodes.Plane020.material} position={[-5.672, 6.379, 0.239]} rotation={[0, 0, -0.003]} scale={[2.497, 1, 0.142]} />
        <mesh castShadow name="Plane022" geometry={nodes.Plane022.geometry} material={nodes.Plane022.material} position={[-5.672, 6.379, 0.959]} rotation={[0, 0, -0.003]} scale={[1.747, 1, 0.142]} />
        <mesh castShadow name="Plane023" geometry={nodes.Plane023.geometry} material={nodes.Plane023.material} position={[-5.672, 6.379, 1.649]} rotation={[0, 0, -0.003]} scale={[2.097, 1, 0.142]} />
        <mesh castShadow name="Cube054" geometry={nodes.Cube054.geometry} material={nodes.Cube054.material} position={[5.937, 4.975, -4.281]} scale={[15.375, 4.05, 0]} />
        <mesh castShadow name="Cube074" geometry={nodes.Cube074.geometry} material={nodes.Cube074.material} position={[5.937, 4.975, 6.059]} scale={[15.375, 4.05, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Room.gltf')
